// Mocks generated by Mockito 5.2.0 from annotations
// in movies_peaple/test/features/persons_list/data/persons_list_remote_data_source_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:movies_peaple/features/popular_persons/data/api_service/api_service.dart'
    as _i3;
import 'package:movies_peaple/features/popular_persons/data/models/popular_people.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakePopularPersonsApiResponse_0 extends _i1.Fake
    implements _i2.PopularPersonsApiResponse {}

/// A class which mocks [PopularPeopleApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularPeopleApiService extends _i1.Mock
    implements _i3.PopularPeopleApiService {
  MockPopularPeopleApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PopularPersonsApiResponse> fetchPopularPersons(int? page) =>
      (super.noSuchMethod(Invocation.method(#fetchPopularPersons, [page]),
              returnValue: Future<_i2.PopularPersonsApiResponse>.value(
                  _FakePopularPersonsApiResponse_0()))
          as _i4.Future<_i2.PopularPersonsApiResponse>);
}
